##########################
# Permission Multipliers #
##########################
EnableXPMultipliers: true
XPMultipliers:
  ex:
    Multiplier: 1.5
    Permission: xpmultiplier.1.5

EnableSuperMobCoinMultipliers: true
SuperMobCoinMultipliers:
  ex:
    Multiplier: 1.5
    Permission: mobcoinmultiplier.1.5
