name: PermissionMultipliers
version: @VERSION@
main: dev.vankka.permissionmultipliers.PermissionMultipliers
api-version: "1.13"
authors: [Vankka]
description: Multipliers through permissions
softdepend: [SuperMobCoins]

commands:
  xpmultipliers:
    permission: permissionmultipliers.reload
    usage: /<command> reload
